import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, LogOut, MessageSquare, WalletCards } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAccount } from "@/lib/auth";
import { LeafMark } from "@/components/app/logo";
import { Button } from "@/components/ui/button";
import { Panel, Pill } from "@/components/app/kit";
export const Route=createFileRoute("/portal")({head:()=>({meta:[{title:"My Patient Portal | MJD Wellness"},{name:"description",content:"Private MJD Wellness patient appointments and contact details."},{property:"og:title",content:"My Patient Portal | MJD Wellness"},{property:"og:description",content:"Private patient appointments and contact details."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Portal});
function Portal(){const account=useAccount();const {data}=useQuery({queryKey:["my-portal",account.session?.user.id],queryFn:async()=>{const {data:patient,error}=await supabase.from("patients").select("*").eq("profile_id",account.session!.user.id).maybeSingle();if(error)throw error;if(!patient)return null;const {data:appointments,error:aError}=await supabase.from("appointments").select("*").eq("patient_id",patient.id).order("starts_at");if(aError)throw aError;return{patient,appointments:appointments??[]}}});return <main className="min-h-screen bg-background"><header className="flex h-14 items-center justify-between border-b border-border px-5"><div className="flex items-center gap-3 text-primary"><LeafMark/><span className="font-semibold text-foreground">MJD Wellness Patient Portal</span></div><Button size="sm" variant="ghost" onClick={()=>void account.signOut()}><LogOut/>Sign out</Button></header><div className="mx-auto max-w-5xl p-5"><h1 className="text-2xl font-semibold">Welcome, {data?.patient.first_name??account.displayName}</h1><p className="mt-1 text-sm text-muted-foreground">Your private account only shows records linked to you.</p>{data?<div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Panel title="Your appointments"><ul className="space-y-3">{data.appointments.map(a=><li key={a.id} className="flex items-center gap-3 border-b border-border pb-3"><CalendarDays className="size-5 text-primary"/><span className="flex-1"><b className="block text-sm">{new Date(a.starts_at).toLocaleString()}</b><small className="text-muted-foreground">{a.appointment_type} · {a.provider_name}</small></span><Pill tone={a.status==="confirmed"?"green":"orange"}>{a.status}</Pill></li>)}</ul></Panel><div className="space-y-5"><Panel title="Contact details"><p className="text-sm">{data.patient.email}</p><p className="text-sm">{data.patient.phone}</p><p className="mt-3 text-xs text-muted-foreground">To change clinical details, contact MJD Wellness.</p></Panel><Panel title="Account"><div className="flex items-center gap-3"><WalletCards className="text-primary"/><span><b className="block">Balance</b><span className="text-sm text-muted-foreground">${(data.patient.balance_cents/100).toFixed(2)}</span></span></div><div className="mt-4 flex items-center gap-3"><MessageSquare className="text-primary"/><span className="text-sm">Secure messaging is connected to your patient record.</span></div></Panel></div></div>:<Panel className="mt-6" title="Account setup"><p className="text-sm text-muted-foreground">Your login is active, but a patient record has not been linked yet. Please contact MJD Wellness.</p></Panel>}</div></main>}