/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as FaxRouteImport } from './routes/fax'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PhoneSettingsRouteImport } from './routes/phone-settings'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TimeLaborRouteImport } from './routes/time-labor'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminFeaturesRouteImport } from './routes/admin/features'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminTelecomRouteImport } from './routes/admin/telecom'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as ApiPublicRepairMjdInvitesRouteImport } from './routes/api/public/repair-mjd-invites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const FaxRoute = FaxRouteImport.update({
  id: '/fax',
  path: '/fax',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneSettingsRoute = PhoneSettingsRouteImport.update({
  id: '/phone-settings',
  path: '/phone-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeLaborRoute = TimeLaborRouteImport.update({
  id: '/time-labor',
  path: '/time-labor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/admin/features',
  path: '/admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTelecomRoute = AdminTelecomRouteImport.update({
  id: '/admin/telecom',
  path: '/admin/telecom',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRepairMjdInvitesRoute =
  ApiPublicRepairMjdInvitesRouteImport.update({
    id: '/api/public/repair-mjd-invites',
    path: '/api/public/repair-mjd-invites',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/fax': typeof FaxRoute
  '/forms': typeof FormsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/patients': typeof PatientsRoute
  '/payments': typeof PaymentsRoute
  '/phone-settings': typeof PhoneSettingsRoute
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/team': typeof TeamRoute
  '/time-labor': typeof TimeLaborRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/telecom': typeof AdminTelecomRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/repair-mjd-invites': typeof ApiPublicRepairMjdInvitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/fax': typeof FaxRoute
  '/forms': typeof FormsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/patients': typeof PatientsRoute
  '/payments': typeof PaymentsRoute
  '/phone-settings': typeof PhoneSettingsRoute
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/team': typeof TeamRoute
  '/time-labor': typeof TimeLaborRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/telecom': typeof AdminTelecomRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/public/repair-mjd-invites': typeof ApiPublicRepairMjdInvitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/fax': typeof FaxRoute
  '/forms': typeof FormsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/patients': typeof PatientsRoute
  '/payments': typeof PaymentsRoute
  '/phone-settings': typeof PhoneSettingsRoute
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/team': typeof TeamRoute
  '/time-labor': typeof TimeLaborRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/telecom': typeof AdminTelecomRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/repair-mjd-invites': typeof ApiPublicRepairMjdInvitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calls'
    | '/fax'
    | '/forms'
    | '/inbox'
    | '/integrations'
    | '/patients'
    | '/payments'
    | '/phone-settings'
    | '/portal'
    | '/reset-password'
    | '/reviews'
    | '/schedule'
    | '/team'
    | '/time-labor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/features'
    | '/admin/health'
    | '/admin/integrations'
    | '/admin/locations'
    | '/admin/organizations'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/telecom'
    | '/admin/users'
    | '/settings/roles'
    | '/admin/'
    | '/settings/'
    | '/api/public/repair-mjd-invites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calls'
    | '/fax'
    | '/forms'
    | '/inbox'
    | '/integrations'
    | '/patients'
    | '/payments'
    | '/phone-settings'
    | '/portal'
    | '/reset-password'
    | '/reviews'
    | '/schedule'
    | '/team'
    | '/time-labor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/features'
    | '/admin/health'
    | '/admin/integrations'
    | '/admin/locations'
    | '/admin/organizations'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/telecom'
    | '/admin/users'
    | '/settings/roles'
    | '/admin'
    | '/settings'
    | '/api/public/repair-mjd-invites'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/calls'
    | '/fax'
    | '/forms'
    | '/inbox'
    | '/integrations'
    | '/patients'
    | '/payments'
    | '/phone-settings'
    | '/portal'
    | '/reset-password'
    | '/reviews'
    | '/schedule'
    | '/team'
    | '/time-labor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/features'
    | '/admin/health'
    | '/admin/integrations'
    | '/admin/locations'
    | '/admin/organizations'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/telecom'
    | '/admin/users'
    | '/settings/roles'
    | '/admin/'
    | '/settings/'
    | '/api/public/repair-mjd-invites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CallsRoute: typeof CallsRoute
  FaxRoute: typeof FaxRoute
  FormsRoute: typeof FormsRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PatientsRoute: typeof PatientsRoute
  PaymentsRoute: typeof PaymentsRoute
  PhoneSettingsRoute: typeof PhoneSettingsRoute
  PortalRoute: typeof PortalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  ScheduleRoute: typeof ScheduleRoute
  TeamRoute: typeof TeamRoute
  TimeLaborRoute: typeof TimeLaborRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTelecomRoute: typeof AdminTelecomRoute
  AdminUsersRoute: typeof AdminUsersRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiPublicRepairMjdInvitesRoute: typeof ApiPublicRepairMjdInvitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fax': {
      id: '/fax'
      path: '/fax'
      fullPath: '/fax'
      preLoaderRoute: typeof FaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-settings': {
      id: '/phone-settings'
      path: '/phone-settings'
      fullPath: '/phone-settings'
      preLoaderRoute: typeof PhoneSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-labor': {
      id: '/time-labor'
      path: '/time-labor'
      fullPath: '/time-labor'
      preLoaderRoute: typeof TimeLaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/admin/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/telecom': {
      id: '/admin/telecom'
      path: '/admin/telecom'
      fullPath: '/admin/telecom'
      preLoaderRoute: typeof AdminTelecomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/repair-mjd-invites': {
      id: '/api/public/repair-mjd-invites'
      path: '/api/public/repair-mjd-invites'
      fullPath: '/api/public/repair-mjd-invites'
      preLoaderRoute: typeof ApiPublicRepairMjdInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CallsRoute: CallsRoute,
  FaxRoute: FaxRoute,
  FormsRoute: FormsRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  PatientsRoute: PatientsRoute,
  PaymentsRoute: PaymentsRoute,
  PhoneSettingsRoute: PhoneSettingsRoute,
  PortalRoute: PortalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  ScheduleRoute: ScheduleRoute,
  TeamRoute: TeamRoute,
  TimeLaborRoute: TimeLaborRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTelecomRoute: AdminTelecomRoute,
  AdminUsersRoute: AdminUsersRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  AdminIndexRoute: AdminIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiPublicRepairMjdInvitesRoute: ApiPublicRepairMjdInvitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
